export const COUNTRY_OPTIONS = [
	{ code: 'DZ', name: 'Algerie', flag: '🇩🇿' },
	{ code: 'DE', name: 'Allemagne', flag: '🇩🇪' },
	{ code: 'SA', name: 'Arabie saoudite', flag: '🇸🇦' },
	{ code: 'BE', name: 'Belgique', flag: '🇧🇪' },
	{ code: 'CA', name: 'Canada', flag: '🇨🇦' },
	{ code: 'CN', name: 'Chine', flag: '🇨🇳' },
	{ code: 'KR', name: 'Coree du Sud', flag: '🇰🇷' },
	{ code: 'DK', name: 'Danemark', flag: '🇩🇰' },
	{ code: 'ES', name: 'Espagne', flag: '🇪🇸' },
	{ code: 'US', name: 'Etats-Unis', flag: '🇺🇸' },
	{ code: 'FI', name: 'Finlande', flag: '🇫🇮' },
	{ code: 'FR', name: 'France', flag: '🇫🇷' },
	{ code: 'GR', name: 'Grece', flag: '🇬🇷' },
	{ code: 'IN', name: 'Inde', flag: '🇮🇳' },
	{ code: 'IT', name: 'Italie', flag: '🇮🇹' },
	{ code: 'JP', name: 'Japon', flag: '🇯🇵' },
	{ code: 'LB', name: 'Liban', flag: '🇱🇧' },
	{ code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
	{ code: 'MA', name: 'Maroc', flag: '🇲🇦' },
	{ code: 'NO', name: 'Norvege', flag: '🇳🇴' },
	{ code: 'NL', name: 'Pays-Bas', flag: '🇳🇱' },
	{ code: 'PL', name: 'Pologne', flag: '🇵🇱' },
	{ code: 'PT', name: 'Portugal', flag: '🇵🇹' },
	{ code: 'GB', name: 'Royaume-Uni', flag: '🇬🇧' },
	{ code: 'SE', name: 'Suede', flag: '🇸🇪' },
	{ code: 'CH', name: 'Suisse', flag: '🇨🇭' },
	{ code: 'TN', name: 'Tunisie', flag: '🇹🇳' },
	{ code: 'TR', name: 'Turquie', flag: '🇹🇷' },
	{ code: 'AE', name: 'Emirats arabes unis', flag: '🇦🇪' },
]

export const countryFlagUrl = (code) => `https://flagcdn.com/w20/${String(code || '').toLowerCase()}.png`
